// import jquery from 'jquery';
import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-material';
import 'angular-ui-router';
import 'angular-ui-sortable';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './components';
import './filters';
import './home';
import './profile';
import './pomreport';
import './services';
import './auth';
import './settings';
import './sidebar';
import './tasks';
import './toast';
import './vendor/javascripts/howler.min.js';
// import './sortable/src/sortable.js';

// Create and bootstrap application
const requires = [  
  'ngMaterial',
  'ui.router',  
  // 'ui.sortable',
  'templates',
  'app.layout',
  'app.components',
  'app.filters',
  'app.home',
  'app.profile',
  'app.pomreport',
  'app.services',
  'app.auth',
  'app.settings',
  'app.sidebar',
  'app.tasks',
  'app.toast'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
